DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilations_events CASCADE;
DROP TABLE IF EXISTS participations CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(250) NOT NULL,
    email               VARCHAR(254) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(50) NOT NULL,
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(2000) NOT NULL,
    category_id         BIGINT NOT NULL
    CONSTRAINT events_category_id_fk
    REFERENCES categories (id) ON DELETE CASCADE,
    confirmed_requests  INTEGER NOT NULL,
    created_on          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description         VARCHAR(7000) NOT NULL,
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id        BIGINT NOT NULL
    CONSTRAINT events_initiator_id_fk
    REFERENCES users (id) ON DELETE CASCADE,
    lat                 FLOAT,
    lon                 FLOAT,
    paid                BOOLEAN NOT NULL,
    participant_limit   INTEGER,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(9) NOT NULL,
    title               VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned              BOOLEAN NOT NULL,
    title               VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilations_id     BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    events_id           BIGINT REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilations_id, events_id)
);

CREATE TABLE IF NOT EXISTS participations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id        BIGINT NOT NULL
    CONSTRAINT participations_requester_id_fk
    REFERENCES users (id) ON DELETE CASCADE,
    event_id            BIGINT NOT NULL
    CONSTRAINT participations_event_id_fk
    REFERENCES events (id) ON DELETE CASCADE,
    created             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status              VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text                VARCHAR(255) NOT NULL,
    event_id            BIGINT NOT NULL
    CONSTRAINT comments_event_id_fk
    REFERENCES events (id) ON DELETE CASCADE,
    author_id           BIGINT NOT NULL
    CONSTRAINT comment_author_id_fk
    REFERENCES users (id) ON DELETE CASCADE,
    created             TIMESTAMP WITHOUT TIME ZONE
    );